### ISSUE TITLE
Discussion and reasoning on license issue

### ISSUE THREAD

**Issue by sgauravm** [UBC-MDS/edar#69]
-  Discuss and reason the license choice by opening issues in both Python and R repositories.
  - Include a link of these issues in your final_project repository's README.md file.

**Comment by sweber15** [comment]
Following our [edapython discussion](https://github.com/UBC-MDS/edapython/issues/93), the MIT license we currently have suits the needs of this project as it is simple and permissive for users of the package and collaborators. This license fits our needs since we are not monetizing it. It allows collaboration and people to use this package without a lot of constraints.

**Comment by v5y8** [comment]
I agree; the MIT license works fine.

**Comment by sgauravm** [comment]
We developed this package for educational purpose and wanted limited restriction. The MIT license is a short and simple permissive license only requiring preserving of copyright and license notices. This correctly fits into our requirement so we all agreed to use the [MIT](https://choosealicense.com/licenses/mit/) license

**Comment by marvinmin** [comment]
True. Based on the purpose of our package, the MIT license is suitable.

**Comment by v5y8** [comment]
Looks like we've reached consensus; we will stick with the MIT license.
